on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Test and build
    environment: snyk-npm
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Setup Snyk + snyk-to-html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH }}
        run: |
          npm install snyk -g
          npm install snyk-to-html -g
          snyk auth "$SNYK_TOKEN"

      - name: Snyk Open Source
        run: |
          snyk monitor

      - name: Snyk Code
        run: |
          snyk code test || true

      - name: Snyk Container
        run: |
          docker build . -t snykgoof:latest
          snyk container monitor snykgoof:latest --file=Dockerfile

      - name: Snyk IaC
        run: |
          snyk iac test || true

# Trigger new pipeline scan